# @format
# https://medium.com/@saad-awais/sync-one-repository-with-another-using-github-actions-1f349eed5173

name: Sync Repos

on:
  push:
    branches:
      - main
  # You can add more triggers, such as scheduled events
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Push to destination repository
        run: |
          git config --global user.email "paul.belfrage@gmail.com"
          git config --global user.name "paubel"
          git clone https://${{ env.ORG_NAME }}:${{ secrets.WEBB_2025 }}@github.com/${{ env.ORG_NAME }}/webbutveckling1.git
          cd webbutveckling1
          git remote add ${{ env.ORIGINAL_REPO_NAME }} https://${{ env.ORG_NAME }}:${{ secrets.WEBB_2025 }}@github.com/${{ env.ORG_NAME }}/${{ env.ORIGINAL_REPO_NAME }}.git
          git remote update
          git merge ${{ env.ORIGINAL_REPO_NAME }}/main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.WEBB_2025 }}
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
          ORG_NAME: Your workspace name
