name: Sync Repos

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: paubel/webbutveckling1
          token: ${{ secrets.PAT }} # Use PAT for private repository

      - name: Push to destination repository
        run: |
          cd ${{ github.workspace }}/webbutveckling1
          git remote add origin https://${{ secrets.PAT }}@github.com/paul-pauliskolan/webbutveckling1.git
          git push origin HEAD:main
