# @format

name: Sync Repos

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Push to destination repository
        run: |
          git config --global user.email "paul.belfrage@skola.malmo.se"
          git config --global user.name "paul-pauliskolan"
          git clone https://${{ secrets.PAT }}@github.com/paubel/webbutveckling1.git
          cd webbutveckling1
          git remote add source-repo https://${{ secrets.PAT }}@github.com/paul-pauliskolan/webbutveckling1.git
          git remote update
          git merge source-repo/main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
